services:
  # Бэкенд сервис
  - type: web
    name: lombard-backend
    env: python
    buildCommand: pip install -r src/backend/requirements.txt
    startCommand: cd src/backend && gunicorn app:app
    envVars:
      - key: DB_NAME
        value: Lombard
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
    plan: free
  
  # Фронтенд сервис
  - type: web
    name: lombard-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: lombard-backend
          type: web
          property: url
    plan: free 